branches:
    only:
        - master

image: Visual Studio 2015

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\llvm
shallow_clone: true

matrix:
    fast_finish: false

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

environment:
    matrix:
        -   TOOLCHAIN: msvc10
            CRT: libcmt

        -   TOOLCHAIN: msvc10
            CRT: msvcrt

        -   TOOLCHAIN: msvc12
            CRT: libcmt

        -   TOOLCHAIN: msvc12
            CRT: msvcrt

        -   TOOLCHAIN: msvc14
            CRT: libcmt

        -   TOOLCHAIN: msvc14
            CRT: msvcrt

install:
    - call set-env.bat %PLATFORM% %TOOLCHAIN% %CRT%
    - call install.bat

build_script:
    - set THIS_DIR=%CD%

    - mkdir llvm\build
    - cd llvm\build
    - cmake .. %CMAKE_FLAGS%
    - cmake --build . -- %MSBUILD_FLAGS%
    - cmake --build . --target install

    - cd %THIS_DIR%

    - perl patch-llvm-config.pl %LLVM_RELEASE_DIR%\share\llvm\cmake\LLVMConfig.cmake

    - echo patched LLVMConfig.cmake:
    - type %LLVM_RELEASE_DIR%\share\llvm\cmake\LLVMConfig.cmake

    - 7z a -t7z %LLVM_RELEASE_FILE% %LLVM_RELEASE_DIR%
