image:
    - Visual Studio 2017
    - Visual Studio 2015

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\llvm
shallow_clone: true

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

environment:
    LLVM_VERSION: 3.9.1

    matrix:
#        -   TOOLCHAIN: msvc10
#            CRT: msvcrt
#
#        -   TOOLCHAIN: msvc10
#            CRT: libcmt

        -   TOOLCHAIN: msvc15
            CRT: msvcrt

        -   TOOLCHAIN: msvc15
            CRT: libcmt

        -   TOOLCHAIN: msvc12
            CRT: msvcrt

        -   TOOLCHAIN: msvc12
            CRT: libcmt

        -   TOOLCHAIN: msvc14
            CRT: msvcrt

        -   TOOLCHAIN: msvc14
            CRT: libcmt

matrix:
    fast_finish: false

    exclude:
        -   image: Visual Studio 2015
            TOOLCHAIN: msvc15

        -   image: Visual Studio 2017
            TOOLCHAIN: msvc10

        -   image: Visual Studio 2017
            TOOLCHAIN: msvc12

        -   image: Visual Studio 2017
            TOOLCHAIN: msvc14


install:
    - call set-env.bat %CONFIGURATION% %PLATFORM% %TOOLCHAIN% %CRT%
    - call install.bat

build_script:
    - set THIS_DIR=%CD%

    - mkdir llvm\build
    - cd llvm\build
    - cmake .. %LLVM_CMAKE_CONFIGURE_FLAGS%
    - cmake --build . %CMAKE_BUILD_FLAGS%
    - cmake --build . --target install %CMAKE_BUILD_FLAGS%

    - cd %THIS_DIR%

    - 7z a -t7z %LLVM_RELEASE_FILE% %LLVM_RELEASE_NAME%

    - dir \

artifacts:
    -   path: $(LLVM_RELEASE_FILE)
        name: llvm_package

deploy:
    description: '$(APPVEYOR_REPO_TAG_NAME)'
    provider: GitHub

    auth_token:
        secure: tJE3cSm72rg6tNs4ESK38HU9IAhN7Eh/3kvQZhQKuUelpHT55L/MiPOhOcCdw26u

    artifact: llvm_package
    force_update: true

    on:
        appveyor_repo_tag: true
